### ISSUE TITLE
请问能不能做一个服务器端的整合包

### ISSUE THREAD

**Issue by yvesgao86** [VillagerGold/Mercury-landing#1]
我在mcbbs和QQ群里都没看到有服务器端的包
,最好是用NUllCraft Minecraft Server Pro

**Comment by wx-weixiao** [comment]
这个开服器已经停止更新了，不是很建议使用，关于服务端这个就看村民想怎么做了

**Comment by VillagerGold** [comment]
我现在没有任何想开辟村民版服务端的想法，如果有大佬愿意帮这个忙，我会大力支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VillagerGold/Mercury-landing"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月30日(星期六) 晚上11:09
收件人:&nbsp;"VillagerGold/Mercury-landing"<Mercury-landing@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [VillagerGold/Mercury-landing] 请问能不能做一个服务器端的整合包 (#1)





 
这个开服器已经停止更新了，不是很建议使用，关于服务端这个就看村民想怎么做了

**Comment by VillagerGold** [comment]
水星迫降重制版已经提供服务端了，请关注村民黄金哔哩哔哩账号后私信加群，然后在群公告打开百度网盘链接即可下载
