### ISSUE TITLE
进不去

### ISSUE THREAD

**Issue by Chain-Tian** [VillagerGold/Mercury-landing#3]
我重装了几遍，但每次我家在95%的MTLIBmod未响应之后就一动不动了

**Comment by zjh790** [comment]
同样问题，大约30多分钟之后在CHisel继续卡

**Comment by VillagerGold** [comment]
请下载最新版的水星迫降重制版Forge版，如果卡在12.5%请删除"c[自定义加载画面]CustomLoadingScreen-1.5.7.jar"模组，如果有其他情况或问题请继续反馈

**Comment by VillagerGold** [comment]
这个问题或许已经过期，我将关闭，如果还有问题请告诉我
