### ISSUE TITLE
地图有bug

### ISSUE THREAD

**Issue by Chenm25** [VillagerGold/Mercury-landing#4]
水星迫降重制版最新的正式版 “[Mercury landing-水星迫降] v6.6七测（HMCL导出）”没有提供压印机所需的模板。
在所有的陨石坑的箱子里都只有已经压印好的三个电路板，所以AE模组的内容都无法继续。
压印机的模板还不能自己合成
这个bug很严重

**Comment by VillagerGold** [comment]
去海底遗迹就可以找到压印模板了，四种海底遗迹分别对应四种压印模板
