### ISSUE TITLE
请教一个关于史莱姆的问题

### ISSUE THREAD

**Issue by Chinotwo** [VillagerGold/Mercury-landing#5]
我在游玩整合包的过程中想建造一个史莱姆农场，利用小地图mod找到了史莱姆区块并挖到了40层以下
挖出来的空间足够而且挂机地点测试在无光照的情况下农场内可以生成普通怪物
但是添加光照之后无法生成史莱姆
请问大概会是什么原因

**Comment by VillagerGold** [comment]
史莱姆球可以通过任务送的史莱姆树苗种植获取
