### ISSUE TITLE
进去说有可能因为 forge mod loader, minecraft forge, custom loading screen 产生的崩溃

### ISSUE THREAD

**Issue by hutao1145141** [VillagerGold/Mercury-landing#8]
**这里是崩溃报告**
https://mclo.gs/rqBGHw0

**Comment by hutao1145141** [comment]
![Uploading 屏幕截图 2023-12-17 161230.png…]()

**Comment by hutao1145141** [comment]
作者大大，Ender IO 与Optifine 冲突，删除后就解决了这个问题，而高清修复是启动器自动下载的，有什么办法自动删除或禁用它吗

**Comment by VillagerGold** [comment]
我无法复现大佬的问题，请下载最新版的水星迫降重制版（Forge版），然后启动检查是否还有这个问题

**Comment by VillagerGold** [comment]
这个问题或许已经过期，我将关闭，如果还有问题请告诉我
